#!/usr/bin/env python
#This file is also included in .git/hooks
import os
import re

inittext='''
# Codegolf-Submissions
All submissions I have made to [Code Golf](https://code.golf/) in various languages. Note that I do not use encoding tricks in my submissions so my ranking is only concerned with bytes (which will be identical to chars).
# Currently In Progress:
'''

tableheader='''
| Language | Bytes | Rank (in bytes)
|:---:|:---:|:---:|
'''

tests=[test for test in os.listdir('.') if os.path.isdir(test)]
tests.remove('.git')

readme = open('README.md','w')
readme.write(inittext)

for t in tests:
    readme.write('## '+t)
    readme.write(tableheader)
    for lang in os.listdir(t):
        b=''
        files=os.listdir(t+'/'+lang)
        if len(files)==1:
            f=open(t+'/'+lang+'/'+files[0],'r')
            b=len(f.read())
            f.close()
        readme.write('|'+lang+'|'+str(b)+'||\n')
    readme.write('\n\n')

readme.close()