#!/usr/bin/env python

import os
from git import Repo
import matplotlib.pyplot as plt
import urllib
from urllib.request import urlopen
import re
from dotenv import load_dotenv

inittext='''
# Codegolf-Submissions
All submissions I have made to [Code Golf](https://code.golf/) in various languages. Note that I do not use encoding tricks in my submissions so my ranking is only concerned with bytes (which will be identical to chars).
# Currently In Progress:
'''

tableheader='''
| Language | Bytes | Rank (in bytes)
|:---:|:---:|:---:|
'''

usagenotes='''
# Installation notes
You can use this repository for your own code.golf exploits as well!<br>
Clone/Fork this repository into your local system. Use requirements.txt to check for any changes for this file.<br>
Use the command `git config core.hooksPath hooks` to assign `hooks\pre-commit` as a hook of this repository (otherwise this README will break!)<br>
At this point, you can replace all the various hole folders with your own submissions. The format in which they must be stored is `<Hole name>/<Language name>/<whatever file>`.
This will ensure the README updates accurately.<br>
It is important to replace my username in `config.env` with your own github username so it can pull your hole ranks.<br>
Don't commit too fast or too many times at once since the hooks web scrap for rank (which might ratelimit your IP).<br>
'''

contribution='''
# Contribution
If you wish to contribute, please first create an relevant issue. If a PR is required, it will be informed to you.<br>
Ensure you mark all your local hole changes as untracked in your branch/fork in case you are to make a PR, so that there is no merge conflicts, and that `config.env` is similarly
untracked.
'''

load_dotenv('config.env')
username=os.getenv('USERNAME')

def drawGraph(tdata,t):
    #Draw bar graph with specific color codes
    plt.style.use('dark_background')

    plt.bar(tdata.keys(),tdata.values())
    plt.xlabel('Lang')
    plt.ylabel('Char count')
    plt.xticks(rotation=45)
    plt.tight_layout()

    plt.savefig(f"charts/{t.replace(' ','_',-1)}.png",bbox_inches='tight',transparent=True)        #Save as a recognizable name for embedding

def getRank(test,lang):
    pg=1
    rank=[]

    #Replace whitespace and capitals in test name
    test = re.sub(r' ','-',test.lower())

    #Replace special chars in lang name
    lang = re.sub(r'\+','p',lang.lower())
    lang = re.sub(r'\#','-sharp',lang)
    lang = re.sub(r'><>','fish',lang)

    #Loop through all rank pages
    while(pg<11):
        try:
            page = urlopen(f'https://code.golf/rankings/holes/{test}/{lang}/bytes?page={pg}')
        except urllib.error.HTTPError:
            break

        html = page.read().decode('utf-8')

        rank=re.findall(fr'<td>([0-9]+)<sup>.*</sup>\n +<td>\n +<a href=\"/golfers/{username}',html)

        if(len(rank)==1):
            break

        pg+=1

    if(rank==[]):
        return 'NA'
    else:
        return rank[0]

tests=[test for test in os.listdir('.') if os.path.isdir(test)]
tests.remove('.git')
tests.remove('hooks')
tests.remove('charts')
if('.elixir_ls' in tests):
    tests.remove('.elixir_ls')

readme = open('README.md','w')
readme.write(inittext)

for t in tests:
    tdata={}                                                            #Dictionary to store language data
    readme.write('## '+t)
    readme.write(tableheader)
    for lang in os.listdir(t):
        b=''
        files=os.listdir(t+'/'+lang)
        if len(files)==1:
            f=open(t+'/'+lang+'/'+files[0],'r')
            b=len(f.read())                                             #Get number of chars in each language
            f.close()
        
        readme.write('|'+lang+'|'+str(b)+'|'+getRank(t,lang)+'|\n')     #Add it to the markdown table
        tdata[lang]=b                                                   #..And to the dictionary

    readme.write('\n\n')
    drawGraph(tdata,t)                                                  #Draww the bar graph with matplotlib
    readme.write(f"![{t}](charts/{t.replace(' ','_',-1)}.png)\n\n")

readme.write(usagenotes)
readme.write(contribution)
readme.close()

#Add the readme changes to the current commit because Git is drunk as hell and doesn't auto-add during hooks
repo = Repo('.').git
repo.add(all=True)
