#!/usr/bin/env python

import os
from git import Repo
import matplotlib.pyplot as plt

#Default color settings for the bar chart
plt.rc_context({'axes.edgecolor':'#FFFFF0', 'xtick.color':'#FFFFF0', 'ytick.color':'#FFFFF0', 'figure.facecolor':'black'})

inittext='''
# Codegolf-Submissions
All submissions I have made to [Code Golf](https://code.golf/) in various languages. Note that I do not use encoding tricks in my submissions so my ranking is only concerned with bytes (which will be identical to chars).
# Currently In Progress:
'''

tableheader='''
| Language | Bytes | Rank (in bytes)
|:---:|:---:|:---:|
'''

usagenotes='''
# Usage Notes
When first cloning this repo ensure you add the pre-commit hook to your .git/hooks folder.<br>
Whenever replacing the pre-commit hook ensure the file extension is removed.<br>
Use requirements.txt to check for any changes for this file.<br>
Use the command `git config core.hooksPath hooks` to assign `hooks\pre-commit` as a hook of this repository (otherwise this README will break!)<br>
'''

def drawGraph(tdata):
    plt.figure(facecolor='Black')
    plt.bar(tdata.keys(),tdata.values(),color='#FFFFF0')
    plt.xlabel("Language",color='#FFFFF0')
    plt.ylabel("Char count",color='#FFFFF0')
    plt.title(t,color='#FFFFF0')
    plt.xticks(rotation=45)
    plt.tight_layout()
    ax=plt.axes()
    ax.spines['top'].set_color('Black')
    ax.spines['right'].set_color('Black')
    ax.set_facecolor(color='Black')
    plt.savefig(f"charts/{t}.png",bbox_inches='tight',transparent=True)        #Save as a recognizable name for embedding

tests=[test for test in os.listdir('.') if os.path.isdir(test)]
tests.remove('.git')
tests.remove('hooks')
tests.remove('charts')
if('.elixir_ls' in tests):
    tests.remove('.elixir_ls')

readme = open('README.md','w')
readme.write(inittext)

for t in tests:
    tdata={}                                        #Dictionary to store language data
    readme.write('## '+t)
    readme.write(tableheader)
    for lang in os.listdir(t):
        b=''
        files=os.listdir(t+'/'+lang)
        if len(files)==1:
            f=open(t+'/'+lang+'/'+files[0],'r')
            b=len(f.read())                         #Get number of chars in each language
            f.close()
        readme.write('|'+lang+'|'+str(b)+'||\n')    #Add it to the markdown table
        tdata[lang]=b                               #..And to the dictionary

    readme.write('\n\n')
    drawGraph(tdata)                                #Draww the bar graph with matplotlib
    readme.write(f'![{t}][charts/{t}.png]\n\n')

readme.write(usagenotes)
readme.close()

#Add the readme changes to the current commit because Git is drunk as hell and doesn't auto-add during hooks
repo = Repo('.').git
repo.add(all=True)
